syntax = "proto3";

package com.github.h3nrique.postalcode.proto;

import "domain/create_request.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

option java_package = "com.github.h3nrique.postalcode.proto";
option java_outer_classname = "PostalCodeRouterProto";
option java_multiple_files = true;

service PostalCodeRouter {
  rpc Create(CreateRequest) returns (google.protobuf.Empty) {
    option (google.api.http) = {
      post: "/v1/postalcode/{postal_code}"
      body: "*"
    };
  }
}
