### list
GET http://localhost:8080/postalcode

### find postal code
POST http://localhost:8080/postalcode
Content-Type: application/json

{ "postalCode": "03568000" }

### load
GET http://localhost:8080/postalcode/03568000

### find postal code using proxy
POST http://localhost:9001/v1/postalcode/03568000
Content-Type: application/json

{ "postalCode": "03568000" }

### get using proxy
GET http://localhost:9001/v1/postalcode/03568000
